spring:
  application:
    name: team-service
  datasource:
    url: jdbc:postgresql://localhost:5432/playermarket
    username: dbadmin
    password: dbadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    import: configserver:http://configserver:8762
  cloud:
    config:
      uri: http://localhost:8762
    service-registry:
      auto-registration:
        enabled: true
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

server:
  port: 9090

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
    register-with-eureka: true